### ISSUE TITLE
We are facing some installation issues with this software

### ISSUE THREAD

**Issue by ZyanyanZ** [timxx/pywpsrpc#102]
**Describe the bug**
Collecting pywpsrpc
  Using cached pywpsrpc-2.3.9.tar.gz (6.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      pyproject.toml: line 5: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
      Traceback (most recent call last):
        File "D:\python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\python\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zheng\AppData\Local\Temp\pip-build-env-vmbcjt5f\overlay\Lib\site-packages\sipbuild\api.py", line 28, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\zheng\AppData\Local\Temp\pip-build-env-vmbcjt5f\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 74, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\zheng\AppData\Local\Temp\pip-build-env-vmbcjt5f\overlay\Lib\site-packages\sipbuild\project.py", line 608, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\zheng\AppData\Local\Temp\pip-build-env-vmbcjt5f\overlay\Lib\site-packages\sipbuild\project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\zheng\AppData\Local\Temp\pip-install-6kkilpva\pywpsrpc_ac34d1f7b61642e199f85e94112f7672\project.py", line 280, in apply_user_defaults     
          raise sipbuild.UserException(
      sipbuild.exceptions.UserException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
**To Reproduce**
pip install pywpsrpc

**Environment**
 - Distribution:
 - Versions: [e.g. pywpsrpc 2.3.9 , WPS Office 11.1.0.9126]
 - Installed from pip: [yes]

**Comment by mjTree** [comment]
> **Describe the bug** Collecting pywpsrpc Using cached pywpsrpc-2.3.9.tar.gz (6.1 MB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [22 lines of output] pyproject.toml: line 5: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead Traceback (most recent call last): File "D:\python\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in main() File "D:\python\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs']) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\python\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 152, in prepare_metadata_for_build_wheel whl_basename = backend.build_wheel(metadata_directory, config_settings) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\zheng\AppData\Local\Temp\pip-build-env-vmbcjt5f\overlay\Lib\site-packages\sipbuild\api.py", line 28, in build_wheel project = AbstractProject.bootstrap('wheel', ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\zheng\AppData\Local\Temp\pip-build-env-vmbcjt5f\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 74, in bootstrap project.setup(pyproject, tool, tool_description) File "C:\Users\zheng\AppData\Local\Temp\pip-build-env-vmbcjt5f\overlay\Lib\site-packages\sipbuild\project.py", line 608, in setup self.apply_user_defaults(tool) File "C:\Users\zheng\AppData\Local\Temp\pip-build-env-vmbcjt5f\overlay\Lib\site-packages\sipbuild\project.py", line 237, in apply_user_defaults self.builder.apply_user_defaults(tool) File "C:\Users\zheng\AppData\Local\Temp\pip-install-6kkilpva\pywpsrpc_ac34d1f7b61642e199f85e94112f7672\project.py", line 280, in apply_user_defaults raise sipbuild.UserException( sipbuild.exceptions.UserException [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details. **To Reproduce** pip install pywpsrpc
> 
> **Environment**
> 
> * Distribution:
> * Versions: [e.g. pywpsrpc 2.3.9 , WPS Office 11.1.0.9126]
> * Installed from pip: [yes]

hi, zheng. you need install in linux system,not windows system
