### ISSUE TITLE
python3.9 无法正常安装库

### ISSUE THREAD

**Issue by sgh317** [timxx/pywpsrpc#85]
执行报错明细如下：

```
dl@DL hgs % pip install pywpsrpc   
Collecting pywpsrpc
  Using cached pywpsrpc-2.3.9.tar.gz (6.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/yw/jt9ztn6j3xs1k6_thf_tk7_80000gn/T/pip-build-env-4_hw_8gx/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/yw/jt9ztn6j3xs1k6_thf_tk7_80000gn/T/pip-build-env-4_hw_8gx/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/yw/jt9ztn6j3xs1k6_thf_tk7_80000gn/T/pip-build-env-4_hw_8gx/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/yw/jt9ztn6j3xs1k6_thf_tk7_80000gn/T/pip-build-env-4_hw_8gx/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "project.py", line 280, in apply_user_defaults
          raise sipbuild.UserException(
      sipbuild.exceptions.UserException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by timxx** [comment]
你这是mac？

**Comment by sgh317** [comment]
对，只能windows使用吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "timxx/pywpsrpc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月21日(星期二) 晚上10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [timxx/pywpsrpc] python3.9 无法正常安装库 (Issue #85)





 
你这是mac？

**Comment by timxx** [comment]
仅支持linux， readme都写了
