### ISSUE TITLE
在银河麒麟arm64平台上安装失败

### ISSUE THREAD

**Issue by yb-ben** [timxx/pywpsrpc#96]
我已经通过sip-wheel 生成了 pywpsrpc-2.3.9-cp36-cp36m-manylinux1_aarch64.whl，然后用pip installl  ，提示  not a supported wheel on this platform

**Comment by kevinhonor** [comment]
为什么我这边编译失败呢

**Comment by puttys** [comment]
> 我已经通过sip-wheel 生成了 pywpsrpc-2.3.9-cp36-cp36m-manylinux1_aarch64.whl，然后用pip installl ，提示 not a supported wheel on this platform

一样的问题，不知道哪里出错了

**Comment by puttys** [comment]
(python4wps) mypc@mypc-pc:~/hetianhe/pywpsrpc-2.3.9$ pip install pip install -vvv *.whl
Using pip 24.2 from /home/mypc/python4wps/lib/python3.8/site-packages/pip (python 3.8)
Non-user install because user site-packages disabled
Disabling truststore because Python version isn't 3.10+
Created temporary directory: /tmp/pip-build-tracker-19dkd_yr
Initialized build tracking at /tmp/pip-build-tracker-19dkd_yr
Created build tracker: /tmp/pip-build-tracker-19dkd_yr
Entered build tracker: /tmp/pip-build-tracker-19dkd_yr
Created temporary directory: /tmp/pip-install-1zh5z5fr
Created temporary directory: /tmp/pip-ephem-wheel-cache-b956azc2
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Disabling truststore because Python version isn't 3.10+
Remote version of pip: 24.2
Local version of pip:  24.2
Was pip installed by pip? True
ERROR: pywpsrpc-2.3.9-cp38-cp38-manylinux_2_5_aarch64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/home/mypc/python4wps/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/home/mypc/python4wps/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "/home/mypc/python4wps/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/home/mypc/python4wps/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "/home/mypc/python4wps/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 76, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/mypc/python4wps/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 539, in collect_root_requirements
    reqs = list(
  File "/home/mypc/python4wps/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 490, in _make_requirements_from_install_req
    self._fail_if_link_is_unsupported_wheel(ireq.link)
  File "/home/mypc/python4wps/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 146, in _fail_if_link_is_unsupported_wheel
    raise UnsupportedWheel(msg)
pip._internal.exceptions.UnsupportedWheel: pywpsrpc-2.3.9-cp38-cp38-manylinux_2_5_aarch64.whl is not a supported wheel on this platform.
Removed build tracker: '/tmp/pip-build-tracker-19dkd_yr'

**Comment by puttys** [comment]
强行unpackwhl包，把里面的WHEEL文件改了，然后再打包，就可以安装了

**Comment by timxx** [comment]
> 强行unpack whl包，把里面的WHEEL文件改了，然后再打包，就可以安装了

具体是哪一块问题呢，我没有arm环境，可以的话提个PR咯

**Comment by kevinhonor** [comment]
> > 强行unpack whl包，把里面的WHEEL文件改了，然后再打包，就可以安装了
> 
> 具体是哪一块问题呢，我没有arm环境，可以的话提个PR咯

使用pip3 debug --verbose查看平台可支持的whl包命名方式，把whl重新命名一下，这个包pywpsrpc-2.3.9-cp36-cp36m-manylinux1_aarch64.whl 应该命名为pywpsrpc-2.3.9-cp36-cp36m-manylinux_aarch64.whl ，然后再安装就可以了

**Comment by bluntsword1986** [comment]
pip在安装whl时会对wheel 文件的平台标签（文件名）进行校验，manylinux1 是基于 CentOS 5 的古老标准（glibc ≤ 2.12），官方从不支持 ARM64（aarch64）架构，因此在麒麟aarch64的系统中pip 会拒绝安装。
解决方法：将whl文件重命名一下即可，后缀改为-linux_aarch64.whl即可，例如：pywpsrpc-2.3.9-cp36-cp36m-linux_aarch64.whl。
另外，新编译了2.3.12的aarch64的whl文件，主要针对比较稳定的python3.8和比较新的python3.13对应的版本。下载链接：
[https://github.com/bluntsword1986/pywpsrpc/releases/tag/2.3.12](url)
